#!/usr/bin/env sh

# Stop the process and return false to
ctrl_c() {
  echo Stoping checks...
  false
}

# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
trap 'ctrl_c' SIGINT

echo
echo "Styling, testing and building project before committing..."
echo

# Prettier check
npm run lint-staged
OUT=$?

if [ $OUT -eq 0 ]; then
  echo "Formated all staged files."
  echo
else
  echo "lint-staged check Failed."
  echo "Run 'npm run lint-staged', add changes and try commit again."
  false
fi

# Perform distribution, testing and docs creation only if the 'src' folder contents are modified.
IS_SRC_MODIFIED=$(git status -s src)

if [ ! -z "$IS_SRC_MODIFIED" -a "$IS_SRC_MODIFIED" != " " ]; then
  echo "Git status:"
  echo $IS_SRC_MODIFIED
  echo
  # Build check
  npm run build
  OUT=$?

  if [ $OUT -eq 0 ]; then
    echo "Distribution creation successful."
    echo
  else
    echo "Distribution creation failed !!!"
    false
  fi

  # Test
  npm run test
  OUT=$?

  if [ $OUT -eq 0 ]; then
    echo "All tests successful."
    echo
  else
    echo "test failed !!!"
    false
  fi

  # Documents creation
  npm run docs:ts
  OUT=$?

  if [ $OUT -eq 0 ]; then
    git add ./docs/* ./README.md
    echo "Documents updated and added to git staging."
    echo
  else
    echo "Document creation failed !!!"
    false
  fi

fi

echo "All checks completed."
echo
