#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Stop the process and return false to
ctrl_c() {
  echo Stoping checks...
  false
}

# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
trap 'ctrl_c' SIGINT

DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | sed 's/.*: //')
CURR_BRANCH=$(git branch --show-current)

echo "DEFAULT_BRANCH: $DEFAULT_BRANCH, CURR_BRANCH: $CURR_BRANCH"
echo
echo "Fetching origin and all branchs from remote"
git fetch --all
git fetch origin $DEFAULT_BRANCH

HAS_CHANGES=$(git rev-list HEAD...origin/master --count)

if [ $HAS_CHANGES != 0 ]; then
  echo
  echo "Pulling '$DEFAULT_BRANCH' branch data"
  # ------------------------------------------------------------
  # --autostash (Automatically create a temporary stash entry before the operation begins)
  # ------------------------------------------------------------
  git pull origin $DEFAULT_BRANCH --no-commit --verbose --ff-only --autostash

  echo
  echo "Auto merged '$CURR_BRANCH' with '$DEFAULT_BRANCH'."
fi
