#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Stop the process and return false to
ctrl_c() {
  echo Stoping checks...
  false
}

# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
trap 'ctrl_c' SIGINT

echo
echo "Styling, testing and building project before committing..."
echo

# Prettier check
npm run lint-staged
OUT=$?

if [ $OUT -eq 0 ]; then
  echo "Formated all staged files."
  echo
else
  echo "lint-staged check Failed."
  echo "Run 'npm run lint-staged', add changes and try commit again."
  false
fi

# Build check
npm run dist
OUT=$?

if [ $OUT -eq 0 ]; then
  echo "Distribution creation successful."
  echo
else
  echo "Distribution creation failed !!!"
  false
fi

# Test
npm test
OUT=$?

if [ $OUT -eq 0 ]; then
  echo "All tests successful."
  echo
else
  echo "test failed !!!"
  false
fi

# Documents creation
npm run docs:md
OUT=$?

if [ $OUT -eq 0 ]; then
  git add ./docs/* ./README.md
  echo "Documents updated and added to git staging."
  echo
else
  echo "Document creation failed !!!"
  false
fi

echo "All checks completed."
echo
